CREATE TABLE IF NOT EXISTS Users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Notes(
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES Users(id),
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL
);
